server:
  port: 18080

rabbitMq:
  host: # 你的虚拟机IP
  port:  # 端口
  virtual-host: /Learning # 虚拟主机
  username:  # 用户名
  password:  # 密码


mysql:
  host: 
  port: 
  username: 
  password: 
  database: 
  
jedis:
  host: 
  port: 
  password: 
  database: 0    #redis数据库的索引号
  maxIdle: 100  #连接池最大空闲数
  minIdle: 0  #连接池最小空闲数
  maxTotal: 100   #连接池最大连接数
  maxWaitMillis: 500  #这是当连接池耗尽时，调用者最大等待时间为500毫秒
  testOnBorrow: false   #这是从连接池获取连接时，是否进行有效性检查设置为false
  testOnReturn: true  #这是向连接池返回连接时，是否进行有效性检查设置为true。

now:
  host:
    ip: 127.0.0.1
    port: 18080

mailSendingService:
  sendRedirect: http://${mailSendingService.frontend.ip}:${mailSendingService.frontend.port}/service?token=%s
  userVerifyUrl: http://%s:%s/utilityBill/signUp/userSignUp/verify?signUpUUID=%s
  backend:
    ip: 127.0.0.1
    port: 18080
  frontend:
    ip: 127.0.0.1
    port: 8081
